### ISSUE TITLE
TODO: Добавить Dockerfile к фронту

### ISSUE THREAD

**Issue by VlaDexa** [kldd0/LCT-hack-2022#1]
Как я понимаю, мы будем запускать несколько контейнеров и давать им "общаться" друг с другом.
Я в Докере почти ничего не понимаю, да и WSL на ноуте не хочет работать, так что прошу кого-нибудь это сделать

**Comment by kldd0** [comment]
Да, отдельные сервисы в разных контейнерах, общение будет cross origin, с разных портов, ща попробую
